// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Dogadjaj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("OrganizatorID")
                        .HasColumnType("int");

                    b.Property<int>("RezervacijaProstoraFK")
                        .HasColumnType("int");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VideoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Vreme")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("OrganizatorID");

                    b.HasIndex("RezervacijaProstoraFK")
                        .IsUnique();

                    b.ToTable("Dogadjaji");
                });

            modelBuilder.Entity("Backend.Models.DraggableItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojMesta")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Left")
                        .HasColumnType("float");

                    b.Property<int>("PlanProstoraID")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<double>("Top")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("PlanProstoraID");

                    b.ToTable("DraggableItems");
                });

            modelBuilder.Entity("Backend.Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Backend.Models.Line", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Corner1FK")
                        .HasColumnType("int");

                    b.Property<int?>("Corner2FK")
                        .HasColumnType("int");

                    b.Property<int>("PlanProstoraID")
                        .HasColumnType("int");

                    b.Property<double>("X1")
                        .HasColumnType("float");

                    b.Property<double>("X2")
                        .HasColumnType("float");

                    b.Property<double>("Y1")
                        .HasColumnType("float");

                    b.Property<double>("Y2")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("Corner1FK")
                        .IsUnique()
                        .HasFilter("[Corner1FK] IS NOT NULL");

                    b.HasIndex("Corner2FK")
                        .IsUnique()
                        .HasFilter("[Corner2FK] IS NOT NULL");

                    b.HasIndex("PlanProstoraID");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("Backend.Models.Ocena", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DogadjajID")
                        .HasColumnType("int");

                    b.Property<string>("Komentar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int>("Vrednost")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DogadjajID");

                    b.HasIndex("KorisnikID");

                    b.ToTable("Ocene");
                });

            modelBuilder.Entity("Backend.Models.PlanProstora", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DogadjajID")
                        .HasColumnType("int");

                    b.Property<int>("ProstorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DogadjajID");

                    b.HasIndex("ProstorID");

                    b.ToTable("PlanoviProstora");
                });

            modelBuilder.Entity("Backend.Models.Prostor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VlasnikProstoraID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VlasnikProstoraID");

                    b.ToTable("Prostori");
                });

            modelBuilder.Entity("Backend.Models.Rezervacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojMesta")
                        .HasColumnType("int");

                    b.Property<int>("DogadjajID")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int?>("StoFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("VremeRezervacije")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DogadjajID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("StoFK")
                        .IsUnique()
                        .HasFilter("[StoFK] IS NOT NULL");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("Backend.Models.RezervacijaProstora", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ProstorID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("VremeDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremeOd")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ProstorID");

                    b.ToTable("RezervacijeProstora");
                });

            modelBuilder.Entity("Backend.Models.Tag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Tagovi");
                });

            modelBuilder.Entity("DogadjajTag", b =>
                {
                    b.Property<int>("DogadjajiID")
                        .HasColumnType("int");

                    b.Property<int>("TagoviID")
                        .HasColumnType("int");

                    b.HasKey("DogadjajiID", "TagoviID");

                    b.HasIndex("TagoviID");

                    b.ToTable("DogadjajTag");
                });

            modelBuilder.Entity("Backend.Models.Dogadjaj", b =>
                {
                    b.HasOne("Backend.Models.Korisnik", "Organizator")
                        .WithMany()
                        .HasForeignKey("OrganizatorID");

                    b.HasOne("Backend.Models.RezervacijaProstora", "RezervacijaProstora")
                        .WithOne("Dogadjaj")
                        .HasForeignKey("Backend.Models.Dogadjaj", "RezervacijaProstoraFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizator");

                    b.Navigation("RezervacijaProstora");
                });

            modelBuilder.Entity("Backend.Models.DraggableItem", b =>
                {
                    b.HasOne("Backend.Models.PlanProstora", "PlanProstora")
                        .WithMany("DraggableItems")
                        .HasForeignKey("PlanProstoraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanProstora");
                });

            modelBuilder.Entity("Backend.Models.Line", b =>
                {
                    b.HasOne("Backend.Models.DraggableItem", "Corner1")
                        .WithOne("Line1")
                        .HasForeignKey("Backend.Models.Line", "Corner1FK");

                    b.HasOne("Backend.Models.DraggableItem", "Corner2")
                        .WithOne("Line2")
                        .HasForeignKey("Backend.Models.Line", "Corner2FK");

                    b.HasOne("Backend.Models.PlanProstora", "PlanProstora")
                        .WithMany("Lines")
                        .HasForeignKey("PlanProstoraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corner1");

                    b.Navigation("Corner2");

                    b.Navigation("PlanProstora");
                });

            modelBuilder.Entity("Backend.Models.Ocena", b =>
                {
                    b.HasOne("Backend.Models.Dogadjaj", "Dogadjaj")
                        .WithMany("Ocene")
                        .HasForeignKey("DogadjajID");

                    b.HasOne("Backend.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID");

                    b.Navigation("Dogadjaj");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("Backend.Models.PlanProstora", b =>
                {
                    b.HasOne("Backend.Models.Dogadjaj", "Dogadjaj")
                        .WithMany()
                        .HasForeignKey("DogadjajID");

                    b.HasOne("Backend.Models.Prostor", "Prostor")
                        .WithMany("PlanoviProstora")
                        .HasForeignKey("ProstorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dogadjaj");

                    b.Navigation("Prostor");
                });

            modelBuilder.Entity("Backend.Models.Prostor", b =>
                {
                    b.HasOne("Backend.Models.Korisnik", "VlasnikProstora")
                        .WithMany()
                        .HasForeignKey("VlasnikProstoraID");

                    b.Navigation("VlasnikProstora");
                });

            modelBuilder.Entity("Backend.Models.Rezervacija", b =>
                {
                    b.HasOne("Backend.Models.Dogadjaj", "Dogadjaj")
                        .WithMany("Rezervacije")
                        .HasForeignKey("DogadjajID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.DraggableItem", "Sto")
                        .WithOne("Rezervacija")
                        .HasForeignKey("Backend.Models.Rezervacija", "StoFK");

                    b.Navigation("Dogadjaj");

                    b.Navigation("Korisnik");

                    b.Navigation("Sto");
                });

            modelBuilder.Entity("Backend.Models.RezervacijaProstora", b =>
                {
                    b.HasOne("Backend.Models.Prostor", "Prostor")
                        .WithMany("Rezervacije")
                        .HasForeignKey("ProstorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prostor");
                });

            modelBuilder.Entity("DogadjajTag", b =>
                {
                    b.HasOne("Backend.Models.Dogadjaj", null)
                        .WithMany()
                        .HasForeignKey("DogadjajiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagoviID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Dogadjaj", b =>
                {
                    b.Navigation("Ocene");

                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("Backend.Models.DraggableItem", b =>
                {
                    b.Navigation("Line1");

                    b.Navigation("Line2");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("Backend.Models.PlanProstora", b =>
                {
                    b.Navigation("DraggableItems");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Backend.Models.Prostor", b =>
                {
                    b.Navigation("PlanoviProstora");

                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("Backend.Models.RezervacijaProstora", b =>
                {
                    b.Navigation("Dogadjaj")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
